import type { BrandConfig } from "./types";

export const BRAND_CATALOG: Record<string, BrandConfig> = {
  codevamp: {
    id: "codevamp",
    name: "CodevaMP Studio",
    basePath: "/",
    tagline: "laboratorio de sistemas interactivos",
    description: "Mini-apps, herramientas y experiencias modulares conectadas.",
    unitType: "core",
    identity: {
      mission: "Construir un ecosistema creativo-tecnico con rutas de producto conectadas.",
      voice: "claro, visual y directo",
    },
    palette: {
      primary: "#ff5a1f",
      primaryStrong: "#ff3d00",
      neutralLight: "#ffffff",
      neutralDark: "#060606",
    },
    quickLinks: [
      { href: "/explorar", label: "Explorar" },
      { href: "/dev", label: "Dev" },
      { href: "/audio", label: "Audio" },
      { href: "/visuales", label: "Visuales" },
      { href: "/dashboard", label: "Dashboard" },
      { href: "/estrategia", label: "Estrategia" },
      { href: "/acerca", label: "Acerca" },
    ],
    homeTileRoutes: {
      lab: "/acerca",
      explorar: "/explorar",
      audio: "/audio",
      dev: "/dev",
      mapa: "/visuales",
      archivo: "/dev",
      comunidad: "/donaciones",
      energia: "/legal",
    },
  },
  dev: {
    id: "dev",
    name: "Dev",
    basePath: "/dev",
    tagline: "ingenieria de producto",
    description: "Subempresa de desarrollo para construir, validar y publicar software colaborativo.",
    unitType: "subcompany",
    parentId: "codevamp",
    identity: {
      mission: "Convertir ideas tecnicas en productos funcionales, publicables y mantenibles.",
      voice: "pragmatico, tecnico y orientado a ejecucion",
    },
    palette: {
      primary: "#16a34a",
      primaryStrong: "#15803d",
      neutralLight: "#ffffff",
      neutralDark: "#050b12",
    },
    quickLinks: [
      { href: "/dev", label: "Inicio" },
      { href: "/dev/studio", label: "Studio" },
      { href: "/dev#published", label: "Publicados" },
    ],
    homeTileRoutes: {},
  },
  visuales: {
    id: "visuales",
    name: "CodevaMP Visuales",
    basePath: "/visuales",
    tagline: "estudio creativo",
    description: "Feed, estudio y publicacion de proyectos visuales.",
    unitType: "subcompany",
    parentId: "codevamp",
    identity: {
      mission: "Dar a creadores una ruta simple para publicar, distribuir y crecer.",
      voice: "visual, cercano y dinamico",
    },
    palette: {
      primary: "#ff5a1f",
      primaryStrong: "#ff3d00",
      neutralLight: "#ffffff",
      neutralDark: "#121215",
    },
    quickLinks: [
      { href: "/visuales", label: "Inicio" },
      { href: "/visuales/app", label: "App" },
      { href: "/auth", label: "Acceso" },
    ],
    homeTileRoutes: {},
  },
  audio: {
    id: "audio",
    name: "CodevaMP Audio",
    basePath: "/audio",
    tagline: "experiencias sonoras",
    description: "Canal reservado para la mini empresa de audio.",
    unitType: "subcompany",
    parentId: "codevamp",
    identity: {
      mission: "Desarrollar experiencias sonoras inmersivas y modulares.",
      voice: "sensorial, sobrio y experimental",
    },
    palette: {
      primary: "#ff5a1f",
      primaryStrong: "#ff3d00",
      neutralLight: "#ffffff",
      neutralDark: "#101114",
    },
    quickLinks: [{ href: "/audio", label: "Audio" }],
    homeTileRoutes: {},
  },
};
